 var dataSource = [
    {"email":'mehrab@gmail.com','potatoes':25,'tags':['abc','def','ggg'],'full_name':'mehrab jamail','last_name':'Jamil', "athlete": "Michael Phelps", "age": 23, "country": "United States", "year": 2008, "date": "24/08/2008", "sport": "Swimming", "gold": 8, "silver": 0, "bronze": 0, "total": 8 }, 
    {"email":'ramesy@gmail.com','potatoes':23,'tags':['abc','def','ggg'],'full_name':'Gordon Ramesey','last_name':'Ramesey', "athlete": "Michael Phelps", "age": 19, "country": "United States", "year": 2004, "date": "29/08/2004", "sport": "Swimming", "gold": 6, "silver": 0, "bronze": 2, "total": 8 }, 
    {"email":'jhon@gmail.com','potatoes':22,'tags':['abc','def','ggg'],'full_name':'john Anthony','last_name':'Anthony', "athlete": "Michael Phelps", "age": 27, "country": "United States", "year": 2012, "date": "12/08/2012", "sport": "Swimming", "gold": 4, "silver": 2, "bronze": 0, "total": 6 }, 
    { "email":'rohan@gmail.com','potatoes':22,'tags':['abc','def','ggg'],'full_name':'Rohan Kapoor','last_name':'Kapoor',"athlete": "Natalie Coughlin", "age": 25, "country": "United States", "year": 2008, "date": "24/08/2008", "sport": "Swimming", "gold": 1, "silver": 2, "bronze": 3, "total": 6 }, 
    {"email":'ashis@gmail.com','potatoes':21,'tags':['abc','def','ggg'],'full_name':'Ashis Thapar','last_name':'Thapar', "athlete": "Aleksey Nemov", "age": 24, "country": "Russia", "year": 2000, "date": "01/10/2000", "sport": "Gymnastics", "gold": 2, "silver": 1, "bronze": 3, "total": 6 }, 
    {"email":'masud@gmail.com','potatoes':27,'tags':['abc','def','ggg'],'full_name':'Mausd Osman','last_name':'Osman', "athlete": "Alicia Coutts", "age": 24, "country": "Australia", "year": 2012, "date": "12/08/2012", "sport": "Swimming", "gold": 1, "silver": 3, "bronze": 1, "total": 5 }, 
    { "email": "missy@gmail.com","potatoes": 17,'tags':['abc','def','ggg'],"full_name": "Missy Franklin","last_name": "Missy Franklin","athlete": "Missy Franklin", "age": 17, "country": "United States", "year": 2012, "date": "12/08/2012", "sport": "Swimming", "gold": 4, "silver": 0, "bronze": 1, "total": 5 }, 
    {"email": "ryan@gmail.com","potatoes": 19,'tags':['abc','def','ggg'],"full_name": "Ryan Lochte", "last_name": "Ryan Lochte","athlete": "Ryan Lochte", "age": 27, "country": "United States", "year": 2012, "date": "12/08/2012", "sport": "Swimming", "gold": 2, "silver": 2, "bronze": 1, "total": 5 }, 
    {"email": "alison@gmail.com", "potatoes": 21,'tags':['abc','def','ggg'],"full_name": "Allison Schmitt","last_name": "Allison Schmitt","athlete": "Allison Schmitt", "age": 22, "country": "United States", "year": 2012, "date": "12/08/2012", "sport": "Swimming", "gold": 3, "silver": 1, "bronze": 1, "total": 5 }, 
    {"email": "natalie@gmail.com", "potatoes": 27,'tags':['abc','def','ggg'],"full_name": "Natalie Coughlin","last_name": "Natalie Coughlin","athlete": "Natalie Coughlin", "age": 21, "country": "United States", "year": 2004, "date": "29/08/2004", "sport": "Swimming", "gold": 2, "silver": 2, "bronze": 1, "total": 5 }, 
    { "email": "ian@gmail.com","potatoes": 26,'tags':['abc','def','ggg'],"full_name": "Ian Thorpe","last_name": "Ian Thorpe", "age": 17, "country": "Australia", "year": 2000, "date": "01/10/2000", "sport": "Swimming", "gold": 3, "silver": 2, "bronze": 0, "total": 5 }, 
    {"email": "dara@gmail.com", "potatoes": 33,'tags':['abc','def','ggg'],"full_name": "Dara Torres","last_name": "Dara Torres","athlete": "Dara Torres", "age": 33, "country": "United States", "year": 2000, "date": "01/10/2000", "sport": "Swimming", "gold": 2, "silver": 0, "bronze": 3, "total": 5 }, 
    {"email": "cindy@gmail.om","potatoes": 31,'tags':['abc','def','ggg'],"full_name": "Cindy Klassen", "last_name": "Cindy Klassen","athlete": "Cindy Klassen", "age": 26, "country": "Canada", "year": 2006, "date": "26/02/2006", "sport": "Speed Skating", "gold": 1, "silver": 2, "bronze": 2, "total": 5 }, 
    {"email": "nastia@gmail.com","potatoes": 33,'tags':['abc','def','ggg'],"full_name": "Nastia Liukin", "last_name": "Nastia Liukin","athlete": "Nastia Liukin", "age": 18, "country": "United States", "year": 2008, "date": "24/08/2008", "sport": "Gymnastics", "gold": 1, "silver": 3, "bronze": 1, "total": 5 }, 
    {"email": "marit@gmail.com", "potatoes": 32,'tags':['abc','def','ggg'],"full_name": "Marit Bjørgen","last_name": "Marit Bjørgen","athlete": "Marit Bjørgen", "age": 29, "country": "Norway", "year": 2010, "date": "28/02/2010", "sport": "Cross Country Skiing", "gold": 3, "silver": 1, "bronze": 1, "total": 5 }, 
    {"email": "sun@gmail.com", "potatoes": 34,'tags':['abc','def','ggg'],"full_name": "Sun Yang","last_name": "Sun Yang","athlete": "Sun Yang", "age": 20, "country": "China", "year": 2012, "date": "12/08/2012", "sport": "Swimming", "gold": 2, "silver": 1, "bronze": 1, "total": 4 }, 
    {"email": "kristy@gmail.com","potatoes": 36,'tags':['abc','def','ggg'],"full_name": "Kirsty Coventry","last_name": "Kirsty Coventry","athlete": "Kirsty Coventry", "age": 24, "country": "Zimbabwe", "year": 2008, "date": "24/08/2008", "sport": "Swimming", "gold": 1, "silver": 3, "bronze": 0, "total": 4 }, 
    {"email": "libby@gmail.com", "potatoes": 18,'tags':['abc','def','ggg'],"full_name": "Libby Lenton-Trickett","last_name": "Libby Lenton-Trickett","athlete": "Libby Lenton-Trickett", "age": 23, "country": "Australia", "year": 2008, "date": "24/08/2008", "sport": "Swimming", "gold": 2, "silver": 1, "bronze": 1, "total": 4 }, 
    {"email": "ryan@gmail.com", "potatoes": 20,'tags':['abc','def','ggg'],"full_name": "Ryan Lochte","last_name": "Ryan Lochte","athlete": "Ryan Lochte", "age": 24, "country": "United States", "year": 2008, "date": "24/08/2008", "sport": "Swimming", "gold": 2, "silver": 0, "bronze": 2, "total": 4 },
    {"email": "amir@gmail.com", "potatoes": 24,'tags':['abc','def','ggg'],"full_name": "Amir Khan","last_name": "Khan","athlete": "Ryan Lochte", "age": 24, "country": "United States", "year": 2008, "date": "24/08/2008", "sport": "Swimming", "gold": 2, "silver": 0, "bronze": 2, "total": 4 }
  ];

  var newDataSource = [

  ]

  export default dataSource;